title: "ğŸ• Kantonslager Solothurn"
description: "Ausschreibungen"
theme: jekyll-theme-cayman
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

include:
  - _includes

sass:
  style: compressed
