title: "Kantonslager Solothurn â€“ Ausschreibungen"
description: "Ressorts, Verantwortungen & Rollen"
theme: jekyll-theme-cayman
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

include:
  - _includes

sass:
  style: compressed
